public class Task2{
  public static void main(String args[]){
	  if(args.length != 0){
		  
		  
		  if(args[0].equals("sheto"))
             System.out.println("Task2 : Check VAlue is Equal = sheto == " + args[0] + " is True");
		 
		 
		 else{       
			 System.out.println("Task2 : Check VAlue is Equal = sheto != " + args[0] + " is False");			 
		 }
  }else{
      System.out.println("No input Arg");
  }
  }
}